#
# Module manifest for module 'TcXaeMgmt'
#
# Generated by: Beckhoff
#
# Generated on: 12/17/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'TcXaeMgmt.psm1'

# Version number of this module.
ModuleVersion = '6.0.188'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '2ff0b895-60af-486d-ab1c-781ab019ea47'

# Author of this module
Author = 'Beckhoff'

# Company or vendor of this module
CompanyName = 'Beckhoff Automation GmbH & Co. KG'

# Copyright statement for this module
Copyright = 'Beckhoff Automation GmbH 2024'

# Description of the functionality provided by this module
Description = 'Cmdlets for Twincat ADS and device management for Powershell Core and Windows Powershell'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = 'TcXaeMgmt.types.ps1xml'

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'TcXaeMgmt.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = 'Add-AdsRoute', 'Close-TcSession', 'Copy-AdsFile', 'Get-AdsRoute', 
               'Get-AdsState', 'Get-TcDataType', 'Get-TcSession', 'Get-TcSymbol', 
               'Get-TcTargetInfo', 'Get-TcVersion', 'New-TcSession', 'Read-TcValue', 
               'Remove-AdsRoute', 'Set-AdsState', 'Test-AdsRoute', 'Write-TcValue', 
               'Get-TcLicense', 'Send-TcReadWrite', 'Register-AdsHandle', 
               'Unregister-AdsHandle', 'Add-MqttRoute', 'Remove-MqttRoute', 
               'Get-MqttRoute', 'Register-AdsNatRoute', 'Restart-AdsComputer', 
               'Stop-AdsComputer', 'Get-TcRouterInfo', 'Get-AmsRouterEndpoint', 
               'Set-AmsRouterEndpoint', 'Get-TcEvent', 'Get-IODevice', 'Get-EcMaster', 
               'Get-EcBoxes', 'Get-EcFrameStatistics', 'Get-IoFreeRun', 
               'Set-IoFreeRun', 'Reset-IoFreeRun', 'Get-RTimeLatency', 
               'Get-RTimePerformance', 'Get-RTimeCpuSettings', 
               'Set-RTimeCpuSettings', 'Start-AdsProcess', 'Set-AmsNetId', 
               'Restart-TwinCAT', 'Get-AmsNetId', 'Get-TcSymbolStatistics'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = '.\about_TcXaeMgmt.help.txt', '.\License.txt', '.\TcXaeMgmt-Help.xml', 
               '.\TcXaeMgmt.format.ps1xml', '.\TcXaeMgmt.psd1', '.\TcXaeMgmt.psm1', 
               '.\TcXaeMgmt.types.ps1xml', 
               '.\netstandard2.0\EtherCAT.Description.dll', 
               '.\netstandard2.0\Microsoft.CSharp.dll', 
               '.\netstandard2.0\Microsoft.Extensions.Logging.Abstractions.dll', 
               '.\netstandard2.0\System.Buffers.dll', 
               '.\netstandard2.0\System.CodeDom.dll', 
               '.\netstandard2.0\System.ComponentModel.Composition.dll', 
               '.\netstandard2.0\System.Configuration.ConfigurationManager.dll', 
               '.\netstandard2.0\System.Management.dll', 
               '.\netstandard2.0\System.Memory.dll', 
               '.\netstandard2.0\System.Numerics.Vectors.dll', 
               '.\netstandard2.0\System.Reactive.dll', 
               '.\netstandard2.0\System.Resources.Extensions.dll', 
               '.\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll', 
               '.\netstandard2.0\System.Security.AccessControl.dll', 
               '.\netstandard2.0\System.Security.Cryptography.ProtectedData.dll', 
               '.\netstandard2.0\System.Security.Permissions.dll', 
               '.\netstandard2.0\System.Security.Principal.Windows.dll', 
               '.\netstandard2.0\System.Text.Encoding.CodePages.dll', 
               '.\netstandard2.0\System.Threading.Tasks.Extensions.dll', 
               '.\netstandard2.0\TwinCAT.Ads.Abstractions.dll', 
               '.\netstandard2.0\TwinCAT.Ads.dll', 
               '.\netstandard2.0\TwinCAT.Ads.Reactive.dll', 
               '.\netstandard2.0\TwinCAT.Ads.Server.dll', 
               '.\netstandard2.0\TwinCAT.Core.dll', 
               '.\netstandard2.0\TwinCAT.Management.dll', 
               '.\netstandard2.0\TwinCAT.SystemService.dll', 
               '.\netstandard2.0\TwinCAT.Utilities.dll', 
               '.\netstandard2.0\de\TwinCAT.Core.resources.dll', 
               '.\netstandard2.0\de\TwinCAT.Utilities.resources.dll'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Powershell','Management','TcXaeMgmt','ADS','Route','Beckhoff','TwinCAT'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/Beckhoff/ADS/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://infosys.beckhoff.com/content/1033/tc3_ads_ps_tcxaemgmt/3972231819.html?id=8731138690123386389'

        # A URL to an icon representing this module.
        IconUri = 'http://nuget.beckhoff.com/image/PSTwinCATInternal.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'Powershell Commandlets for TwinCAT ADS Communication and TwinCAT Ads Management tasks.

Prerequisites:
>= TwinCAT 3.1.4024.10 (XAR Runtime or Full) (local installation)
>= .NET Framework 4.6.1
>= Windows Powershell 5.1
>= Powershell (Core) 6.0

Note:
This version of the TcXaeMgmt Module only works with TwinCAT Versions >= 4024.10
locally installed. If an older TwinCAT Version is used on the system, please install
the 3.X Series of the TcXaeModule for Windows Powershell.

Features:
- Read/Write Values to Local or Remote Systems via ADS (Symbolic, Raw ProcessImage Data)
- Start-Stop logical ADS Devices (PLC, SystemService) and setting Config Mode locally and remote
- Collection Remote Target System Information (TwinCAT Version)
- Broadcast Search (Browsing ADS Network infrastucture)
- Adding / Removing ADS Routes
- Session Management (ADS Sessions and connections)
- Browsing symbolic information from TwinCAT Targets

First Steps:

Getting global information
```powershell
PS> get-help about_TcXaeMgmt
```

Getting List of commands
```powershell
PS> get-command -module TcXaeMgmt
```

Getting Command Help:
```powershell
PS> get-help Read-TcValue -full
```
Documentation and further learning

[Documentation TcXaeMgmt Module]
https://infosys.beckhoff.com/content/1033/tc3_ads_ps_tcxaemgmt/3972231819.html?id=8731138690123386389
[About the TcXaeMgmt Module]
https://infosys.beckhoff.com/content/1033/tc3_ads_ps_tcxaemgmt/4130762891.html?id=4912948515382920501

ReleaseNotes:

Links
[Beckhoff Homepage]
https://www.beckhoff.com/'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $true

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://infosys.beckhoff.com/content/1033/tc3_ads_ps_tcxaemgmt/9007203226972811.html?id=7774230398660908516'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

